/* Modelagem basica  */

CLIENTE

NOME CARACTERE (30)
CPF NUMERICO (11)
EMAIL CARACTERE(30)
TELEFONE CARACTERE(30)
SEXO CARACTERE(1)
ENDERECO CARACTERE(100)

/* PROCESSOS DE MODELAGEM */

/* ADM DE DADOS */
MODELAGEM CONCEITUAL - RASCUNHO 
MODELAGEM LOGICA - PROGRAMAS COMO BRMODELO

/* AD OU DBA */
MODELAGEM FISICA - SCRIPT DO BANCO DE DADOS

/* MODELO FISICO */

/* CRIANDO UM BANCO */

CREATE DATABASE PROJETO;

/*CONECTAR-SE AO BANCO */

USE PROJETO;

/* CRIAR TABELA*/

CREATE TABLE CLIENTE(
    NOME VARCHAR(30),
    SEXO CHAR(1),
    EMAIL VARCHAR(30),
    CPF VARCHAR(11), 
    TELEFONE VARCHAR(30),
    ENDERECO VARCHAR(100)
);

/* VERIFICAR TABELAS*/
SHOW TABLES;

/*DESCREVENDO A TABELA */
DESC CLIENTE;

INSERT INTO CLIENTE (
    NOME,
    SEXO, 
    EMAIL,
    CPF,
    TELEFONE,
    ENDERECO
) VALUES (
    'MARCELO MORAIS',
    'M',
    'MARCELO@GMAIL.COM', 
    '12345678910',
    '85989898989',
    'RUA DE TESTE 123 FORTALEZA'
);

INSERT INTO CLIENTE VALUES (
    'ELISA MORAIS',
    'F',
    'ELISA@GMAIL.COM', 
    '01987654321',
    '85988889888',
    'RUA DE TESTE 456 FORTALEZA'
);

INSERT INTO CLIENTE VALUES (
    'ESTHER MORAIS',
    'F',
    'ESTHER@GMAIL.COM', 
    '56985654321',
    '85988889888',
    'RUA DE TESTE 789 FORTALEZA'
);

INSERT INTO CLIENTE (
    NOME,
    SEXO, 
    EMAIL,
    CPF,
    TELEFONE,
    ENDERECO
) VALUES (
    'DOM MORAIS',
    'M',
    NULL, 
    '12345678910',
    '85989898989',
    'RUA DE TESTE 023 FORTALEZA CE'
);

INSERT INTO CLIENTE VALUES (
    'FRANCISCO MORAIS',
    'M',
    NULL, 
    '56985654321',
    '85988889888',
    'RUA DE TESTE 789 MARACANAU - CE'
);

SELECT NOW(); /*DATA E HORA DO BANCO*/

/*ALIAS DE COLUNAS */

SELECT 'MARCELO' AS PROFESSOR;

SELECT NOME, SEXO, EMAIL FROM CLIENTE;

SELECT * FROM CLIENTE;

/* FILTRAR DADOS */
/*LIKE % */
SELECT NOME, EMAIL FROM CLIENTE WHERE SEXO = 'M';
SELECT NOME, ENDERECO FROM CLIENTE WHERE ENDERECO LIKE '%FORTALEZA%';

SELECT NOME, EMAIL FROM CLIENTE WHERE SEXO = 'M' OR ENDERECO LIKE '%CE%';


/* COUNT */

SELECT COUNT(*) FROM CLIENTE;
SELECT SEXO, COUNT(*) AS "QUANTIDADE" FROM CLIENTE
 GROUP BY SEXO;

 /*FILTRANDO VALORES NULL */

 SELECT NOME, ENDERECO, EMAIL FROM CLIENTE WHERE EMAIL IS NULL;

 /* UPDATE - SEMPRE COM WHERE */

 SELECT NOME, EMAIL FROM CLIENTE;

 UPDATE CLIENTE 
 SET EMAIL = 'DOM@GMAIL.COM' 
 WHERE NOME = 'DOM MORAIS';

 UPDATE CLIENTE 
 SET EMAIL = 'FRANCISCO@GMAIL.COM' 
 WHERE NOME = 'FRANCISCO MORAIS';

 /* DELETE - SEMPRE COM WHERE */

 DELETE FROM CLIENTE
 WHERE NOME = 'FRANCISCO MORAIS';

/* PRIMEIRA FORMA NORMAL */
/*  
    1 - TODO CAMPO VETORIZADO SE TORNARA OUTRA TABELA - [AZUL, VERDE, AMARELO] VETOR
    2 - TODO CAMPO MULTIVALORADO SE TORNARA OUTRA TABELA - DIVISIVEL
    3 - TODA TABELA NECESSITA DE PELO MENOS UM CAMPO QUE IDENTIFIQUE TODO REGISTO COMO SENDO UNICO -
        CHAVE PRIMARIA
*/    

CREATE DATABASE COMERCIO;
USE COMERCIO;

CREATE TABLE CLIENTE(
    IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30) NOT NULL, 
    SEXO ENUM('M', 'F') NOT NULL,
    EMAIL VARCHAR(50) UNIQUE,
    CPF VARCHAR(15) NOT NULL UNIQUE

);

CREATE TABLE TELEFONE(
    IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
    TIPO ENUM('COM', 'RES', 'CEL'),
    NUMERO VARCHAR(10),
    ID_CLIENTE INT, 
    FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE)
);

CREATE TABLE ENDERECO(
    IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
    RUA VARCHAR(30) NOT NULL,
    BAIRRO VARCHAR(30) NOT NULL,
    CIDADE VARCHAR(30) NOT NULL,
    ESTADO CHAR(2) NOT NULL,
    ID_CLIENTE INT UNIQUE,
    FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE)
);

/* FOREIGN KEY - CHAVE ESTRANGEIRA - FK*/
/* CHAVE PRIMARIA DE UMA TABELA QUE VAI ATE OUTRA TABELA FAZER REFERENCIA */
/* EM RELACIONAMENTO 1 X 1 A CHAVE ESTRANGEIRA FICA NA TABELA MAIS FRACA */
/* EM REALACIONAMETOS 1 X N A CHAVE ESTRANGEIRA FICARA SEMPRE NA TABELA N */

SHOW TABLES;

DESC CLIENTE;

INSERT INTO CLIENTE 
VALUES
    (NULL, 'JOAO', 'M', 'JOAO@GMAIL.COM', '98745-6'),
    (NULL, 'CARLOS', 'M', 'CARLOS@GMAIL.COM', '1234-6'),
    (NULL, 'ANA', 'F', 'ANA@GMAIL.COM', '7859-6'),
    (NULL, 'JORGE', 'M', 'JORGE@GMAIL.COM', '999888-6'),
    (NULL, 'CLARA', 'F', NULL, '963258-6'),
    (NULL, 'CELIA', 'F', 'CELIA@GMAIL.COM', '986532-6');

SELECT * FROM CLIENTE;  
DESC ENDERECO;  

INSERT INTO ENDERECO
VALUES
    (NULL, 'RUA FRANCISCO RAMOS 755', 'GENIBAU', 'FORTALEZA', 'CE', 1),
    (NULL, 'RUA PORTO DAS ROSAS 325', 'GENIBAU', 'FORTALEZA', 'CE', 3),
    (NULL, 'RUA CECIL SALGADO 818', 'QUINTINO CUNHA', 'FORTALEZA', 'CE', 2),
    (NULL, 'RUA FLORIANOPOLIS 155', 'HENRIQUE JORGE', 'FORTALEZA', 'CE', 4),
    (NULL, 'RUA 24 DE MAIO 195', 'CENTRO', 'FORTALEZA', 'CE', 5),
    (NULL, 'AV BEZERRA DE MENEZES 2155', 'RODOLFO TEOFILO', 'FORTALEZA', 'CE', 6);

SELECT * FROM ENDERECO;    

DESC TELEFONE;

INSERT INTO TELEFONE
VALUES
    (NULL, 'CEL', '989592956', 2),
    (NULL, 'COM', '989563220', 2),
    (NULL, 'RES', '996655222', 2),
    (NULL, 'CEL', '925628132', 1),
    (NULL, 'COM', '274196325', 3),
    (NULL, 'RES', '987563521', 4),
    (NULL, 'CEL', '988888899', 4),
    (NULL, 'COM', '665898952', 3),
    (NULL, 'CEL', '321045686', 1),
    (NULL, 'RES', '932659878', 1);

SELECT * FROM CLIENTE;

/* SELECAO, PROJECAO E JUNCAO */
/* PROJECAO - TUDO QUE QUEREMOS PROJETAR NA TELA */
SELECT NOME, NOW() AS "DATA" FROM CLIENTE;

/* SELECAO - TEORIA DOS CONJUNTOS */
SELECT NOME, SEXO FROM CLIENTE
    WHERE SEXO = 'M'; /* SELECAO O WHERE É CLAUSULA DE SELECAO*/

/* JUNCAO */    
/* NOME, SEXO, BAIRRO, CIDADE, DATA */
SELECT NOME, SEXO, BAIRRO, CIDADE, NOW() AS "DATA" 
FROM CLIENTE, ENDERECO
WHERE IDCLIENTE = ID_CLIENTE;

SELECT NOME, SEXO, BAIRRO, CIDADE, NOW() AS "DATA" 
FROM CLIENTE, ENDERECO
WHERE IDCLIENTE = ID_CLIENTE AND BAIRRO = 'CENTRO'; /* NUNCA FAZER ISSO */

/* JOIN */

SELECT NOME, SEXO, BAIRRO, CIDADE /*PROJECAO*/
FROM CLIENTE
INER JOIN ENDERECO /*JUNCAO*/
ON IDCLIENTE = ID_CLIENTE
WHERE BAIRRO = 'CENTRO'; /*SELECAO*/

SELECT CLIENTE.NOME, CLIENTE.SEXO, ENDERECO.BAIRRO, ENDERECO.CIDADE, TELEFONE.TIPO, TELEFONE.NUMERO /*PROJECAO*/
FROM CLIENTE
INNER JOIN ENDERECO /*JUNCAO*/
ON CLIENTE.IDCLIENTE = ENDERECO.ID_CLIENTE
INNER JOIN TELEFONE
ON CLIENTE.IDCLIENTE = TELEFONE.ID_CLIENTE;

SELECT C.NOME, C.SEXO, E.BAIRRO, E.CIDADE, T.TIPO, T.NUMERO /*PROJECAO*/
FROM CLIENTE C
INNER JOIN ENDERECO E /*JUNCAO*/
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
WHERE SEXO = 'M';

/* QUERIES - SELECAO - PROJECAO - E JUNCAO*/
/* PARA UMA CAMPANHA DE MARKETING, O SETOR SOLICITOU UM RELATORIO COM O NOME, EMAIL, E TELEFONE CELULAR DOS CLIENTES QUE MORAM NO ESTADO DO CE. VOCE TERA QUE PASSAR A QUERY PARA GERAR O RELATORIO PARA O PROGRAMADOR */

SELECT C.NOME, C.EMAIL, T.NUMERO, E.ESTADO
FROM CLIENTE C
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
WHERE T.TIPO = 'CEL' AND E.ESTADO = 'CE';

/* IFNULL */

SELECT C.NOME, 
       C.EMAIL,
       T.NUMERO
FROM CLIENTE C
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE;  

SELECT C.NOME, IFNULL(C.EMAIL, 'SEM EMAIL') AS "EMAIL"
FROM CLIENTE C;



