/* Modelagem basica  */

CLIENTE

NOME CARACTERE (30)
CPF NUMERICO (11)
EMAIL CARACTERE(30)
TELEFONE CARACTERE(30)
SEXO CARACTERE(1)
ENDERECO CARACTERE(100)

/* PROCESSOS DE MODELAGEM */

/* ADM DE DADOS */
MODELAGEM CONCEITUAL - RASCUNHO 
MODELAGEM LOGICA - PROGRAMAS COMO BRMODELO

/* AD OU DBA */
MODELAGEM FISICA - SCRIPT DO BANCO DE DADOS

/* MODELO FISICO */

/* CRIANDO UM BANCO */

CREATE DATABASE PROJETO;

/*CONECTAR-SE AO BANCO */

USE PROJETO;

/* CRIAR TABELA*/

CREATE TABLE CLIENTE(
    NOME VARCHAR(30),
    SEXO CHAR(1),
    EMAIL VARCHAR(30),
    CPF VARCHAR(11), 
    TELEFONE VARCHAR(30),
    ENDERECO VARCHAR(100)
);

/* VERIFICAR TABELAS*/
SHOW TABLES;

/*DESCREVENDO A TABELA */
DESC CLIENTE;

INSERT INTO CLIENTE (
    NOME,
    SEXO, 
    EMAIL,
    CPF,
    TELEFONE,
    ENDERECO
) VALUES (
    'MARCELO MORAIS',
    'M',
    'MARCELO@GMAIL.COM', 
    '12345678910',
    '85989898989',
    'RUA DE TESTE 123 FORTALEZA'
);

INSERT INTO CLIENTE VALUES (
    'ELISA MORAIS',
    'F',
    'ELISA@GMAIL.COM', 
    '01987654321',
    '85988889888',
    'RUA DE TESTE 456 FORTALEZA'
);

INSERT INTO CLIENTE VALUES (
    'ESTHER MORAIS',
    'F',
    'ESTHER@GMAIL.COM', 
    '56985654321',
    '85988889888',
    'RUA DE TESTE 789 FORTALEZA'
);

INSERT INTO CLIENTE (
    NOME,
    SEXO, 
    EMAIL,
    CPF,
    TELEFONE,
    ENDERECO
) VALUES (
    'DOM MORAIS',
    'M',
    NULL, 
    '12345678910',
    '85989898989',
    'RUA DE TESTE 023 FORTALEZA CE'
);

INSERT INTO CLIENTE VALUES (
    'FRANCISCO MORAIS',
    'M',
    NULL, 
    '56985654321',
    '85988889888',
    'RUA DE TESTE 789 MARACANAU - CE'
);

SELECT NOW(); /*DATA E HORA DO BANCO*/

/*ALIAS DE COLUNAS */

SELECT 'MARCELO' AS PROFESSOR;

SELECT NOME, SEXO, EMAIL FROM CLIENTE;

SELECT * FROM CLIENTE;

/* FILTRAR DADOS */
/*LIKE % */
SELECT NOME, EMAIL FROM CLIENTE WHERE SEXO = 'M';
SELECT NOME, ENDERECO FROM CLIENTE WHERE ENDERECO LIKE '%FORTALEZA%';

SELECT NOME, EMAIL FROM CLIENTE WHERE SEXO = 'M' OR ENDERECO LIKE '%CE%';


/* COUNT */

SELECT COUNT(*) FROM CLIENTE;
SELECT SEXO, COUNT(*) AS "QUANTIDADE" FROM CLIENTE
 GROUP BY SEXO;

 /*FILTRANDO VALORES NULL */

 SELECT NOME, ENDERECO, EMAIL FROM CLIENTE WHERE EMAIL IS NULL;

 /* UPDATE - SEMPRE COM WHERE */

 SELECT NOME, EMAIL FROM CLIENTE;

 UPDATE CLIENTE 
 SET EMAIL = 'DOM@GMAIL.COM' 
 WHERE NOME = 'DOM MORAIS';

 UPDATE CLIENTE 
 SET EMAIL = 'FRANCISCO@GMAIL.COM' 
 WHERE NOME = 'FRANCISCO MORAIS';

 /* DELETE - SEMPRE COM WHERE */

 DELETE FROM CLIENTE
 WHERE NOME = 'FRANCISCO MORAIS';





